source 'https://cdn.cocoapods.org/'
platform :ios, '15.2'

target 'GitFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitFeed
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'

end
